### ISSUE TITLE
Vulnerability Remediation

### ISSUE THREAD

**Issue by drealuc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#118]
From @mdboone06  @eveandsn noted on report (https://ibm.box.com/s/xssiwpdrf21n7vujz71d56qemifbp0v4)
Please advise on @davidnixon response to your vulnerability concerns 
Do not think these items are application. The yarn package manager has provided the following result:
yarn audit
yarn audit v1.22.5
0 vulnerabilities found - Packages audited: 1649
Done in 1.69s.

**Comment by davidnixon** [comment]
[Five Fifths Scan 101920.pdf](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/files/5409046/Five.Fifths.Scan.101920.pdf)

We no longer have any iframes on the site but we still include an iframe helper component. The report may be seeing that. Since it's not used we can remove it.

**Comment by drealuc** [comment]
@mdboone06 Have you run the app scan yet?

**Comment by davidnixon** [comment]
@drealuc I think this should be closed.
