### ISSUE TITLE
Dependency review

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#141]
I think Christine did a review of this earlier but I can't assign her as an owner. Not sure why. @cstefano1 
I added the Amplitude for the site analytics and that reminded me that there is a top level list of dependencies in the code that we may not have looked at. They are included in the package.json file. I think they are all OK but here are the non-IBM dependencies and a link to their licenses.

dependency | License|Type
-----------------| -----------|----
@babel/core | https://github.com/babel/babel/blob/main/LICENSE |MIT
 amplitude-js | https://github.com/amplitude/Amplitude-JavaScript/blob/master/LICENSE|MIT
axios|https://github.com/axios/axios/blob/master/LICENSE|MIT
core-js|https://github.com/zloirock/core-js/blob/master/LICENSE|MIT
google-maps-api-loader|https://github.com/laurencedorman/google-maps-api-loader/blob/master/LICENSE.md|MIT
lit-element|http://polymer.github.io/LICENSE.txt and https://github.com/Polymer/lit-element/blob/master/LICENSE|BSD
lit-html|http://polymer.github.io/LICENSE.txt and https://github.com/Polymer/lit-html/blob/master/LICENSE|BSD
vue|https://github.com/vuejs/vue/blob/dev/LICENSE|MIT
vue-amplitude|https://github.com/Calvin-Huang/vue-amplitude/blob/master/LICENSE|MIT
vue-router|https://github.com/vuejs/vue-router/blob/dev/LICENSE|MIT
vuejs-countdown|https://github.com/getanwar/vuejs-countdown/blob/master/LICENSE|MIT
webpack|https://github.com/webpack/webpack/blob/master/LICENSE|MIT

These are only the top level. Each of the ones above each have a list of dependencies that they use. So that the entire tree of dependencies is about 1000 modules.

If these look ok I think you can close this. If you need more info, let me now.

**Comment by cstefano1** [comment]
FYI, I...don't know how to interact with git other than to post comments.  Sorry.
 
Thx --
 
Christine StefanoProject Manager, Provider ConsultingIBM Watson Health™
71 South Wacker Drive, Chicago, IL, 60606
(312) 529-1548 office
cstefano@us.ibm.com 
Truven Health Analytics® is now part of the IBM Watson Health business 
 
 
----- Original message -----From: David Nixon <notifications@github.com>To: Call-for-Code-for-Racial-Justice/Five-Fifths-Voter <Five-Fifths-Voter@noreply.github.com>Cc: Christine Stefano <cstefano@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter] Dependency review (#141)Date: Mon, Nov 2, 2020 5:17 PM 
 
I think Christine did a review of this earlier but I can't assign her as an owner. Not sure why. @cstefano1I added the Amplitude for the site analytics and that reminded me that there is a top level list of dependencies in the code that we may not have looked at. They are included in the package.json file. I think they are all OK but here are the non-IBM dependencies and a link to their licenses.
                                                dependency                        License                        Type                                                                        @babel/core                        https://github.com/babel/babel/blob/main/LICENSE                        MIT                                                        amplitude-js                        https://github.com/amplitude/Amplitude-JavaScript/blob/master/LICENSE                        MIT                                                        axios                        https://github.com/axios/axios/blob/master/LICENSE                        MIT                                                        core-js                        https://github.com/zloirock/core-js/blob/master/LICENSE                        MIT                                                        google-maps-api-loader                        https://github.com/laurencedorman/google-maps-api-loader/blob/master/LICENSE.md                        MIT                                                        lit-element                        http://polymer.github.io/LICENSE.txt and https://github.com/Polymer/lit-element/blob/master/LICENSE                        BSD                                                        lit-html                        http://polymer.github.io/LICENSE.txt and https://github.com/Polymer/lit-html/blob/master/LICENSE                        BSD                                                        vue                        https://github.com/vuejs/vue/blob/dev/LICENSE                        MIT                                                        vue-amplitude                        https://github.com/Calvin-Huang/vue-amplitude/blob/master/LICENSE                        MIT                                                        vue-router                        https://github.com/vuejs/vue-router/blob/dev/LICENSE                        MIT                                                        vuejs-countdown                        https://github.com/getanwar/vuejs-countdown/blob/master/LICENSE                        MIT                                                        webpack                        https://github.com/webpack/webpack/blob/master/LICENSE                        MIT                        
These are only the top level. Each of the ones above each have a list of dependencies that they use. So that the entire tree of dependencies is about 1000 modules.
If these look ok I think you can close this. If you need more info, let me now.

**Comment by davidnixon** [comment]
A couple of more stats. I counted production-only dependencies and there are only 550 including the ones above.

License|Number of modules
----|----
MIT|413
Apache-2.0|42
ISC|39
BSD-3-Clause|15
BSD-2-Clause|13
0BSD|1
Unlicense|1
MIT AND Zlib|1
MIT AND BSD-3-Clause|1
MPL-2.0 OR Apache-2.0|1
Not Specified|23

**Comment by drealuc** [comment]
@yrabun Hi Yolanda. Do we need to still address this issue?

**Comment by cstefano1** [comment]
Per @davidnixon this can be closed.
