### ISSUE TITLE
Need to Renew Certificate for www.fivefifthsvoter.com

### ISSUE THREAD

**Issue by yrabun** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#148]
Our certificate for www.fivefifthsvoter.com will expire on **Jan 16, 2021.**  @davidnixon shall we set a time to renew?

**Comment by krook** [comment]
Thoughts @davidnixon?

**Comment by davidnixon** [comment]
Hi guys. Justing getting back after the holidays. Yolanda do you have some time after lunch today? Maybe 2pm? We'll do the same thing we did before to create the new certificate.
 
Dan, what's the latest on moving from open shift to cloud foundry? Do we have org provisioned etc? I have not caught up on slack or email yet.
David Nixon 
                                                                        IBM Global Client Center - Lead Engineer for Interactive 3D Content                         E-mail: david_nixon@us.ibm.com
                        Slack @david_nixon.                                                                                                                                                                                                                                                                                                           
 
 
----- Original message -----From: Daniel Krook <notifications@github.com>To: Call-for-Code-for-Racial-Justice/Five-Fifths-Voter <Five-Fifths-Voter@noreply.github.com>Cc: David Nixon <david_nixon@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter] Need to Renew Certificate for www.fivefifthsvoter.com (#148)Date: Tue, Jan 5, 2021 12:38 PM 
 
Thoughts @davidnixon?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yrabun** [comment]
Thanks for the meetup!! We are all set!
