### ISSUE TITLE
Design for User Login

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#173]
### Background on the problem the feature will solve/improved user experience
Need a design for the User Login and what they can do once they log in.

### Describe the solution you'd like
Related to #172 
I hear that @sebastianhuynh-nyc and @aleggett23 are going to work on this.

### Tasks 
@davidnixon asks that the designer(s) please rank the functions/screens in order of priority.

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by sebastianhuynh-nyc** [comment]
@cstefano1 
I will send the wires I design to the dev team. 
Thank you

**Comment by aleggett23** [comment]
Thanks!
@cstefano1 @davidnixon Would you prefer that the functions be listed here or sent via email?

**Comment by cstefano1** [comment]
@aleggett23 I defer to @sebastianhuynh-nyc and @davidnixon

**Comment by sebastianhuynh-nyc** [comment]
hi @Alexandria, 
what do you mean the lists?

 
 
 
 
 
Sebastian Huynh
Design Lead
Industry Marketing
 
IBM ORIGINALS
 

 
 
Sebastian Huynh
E-mail: ***@***.***
 
 
----- Original message -----From: "Christine Stefano" ***@***.***>To: "Call-for-Code-for-Racial-Justice/Five-Fifths-Voter" ***@***.***>Cc: "sebastianhuynh-nyc" ***@***.***>, "Mention" ***@***.***>Subject: [EXTERNAL] Re: [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter] Design for User Login (#173)Date: Tue, Aug 17, 2021 11:42 AM      @aleggett23 I defer to @sebastianhuynh-nyc and @davidnixon — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@aleggett23 I defer to @sebastianhuynh-nyc and @davidnixon

**Comment by aleggett23** [comment]
No worries, @davidnixon @sebastianhuynh-nyc would it be best for visibility to place log-in notes in comments here as we discussed yesterday or is elsewhere? 

@sebastianhuynh-nyc 

By lists I was referring to some of the functions/options/preferences made available to users when they choose to create an account. You and I had begun fleshing out some ideas last year, and I remember we had generated a temporary beta version to see how things would look. 

It may be good for us to collaborate and share ideas. I was looking for calendar time for us to chat so maybe we can speak on that as well

**Comment by aleggett23** [comment]
Suggestions for Create an Account: 

> Sign Up /Log In Tabs

Sign Up:
> Name, Home Address\Location, Contact Info (Phone/Email), 

Preferences : 

> Ability to select language 

> Ability to select whether to receive notifications
  - Notifications include but not limited to: 
    - Upcoming elections 
    - Voting Registration deadlines based on user location 
    -
  
> Ability to select to receive news information
   - User can select to only receive news on a particular party or candidate or to receive all news.  via (drop down box)
   - 

* still working on note, will return to finish*
