### ISSUE TITLE
Voter Journey Text Requires Update

### ISSUE THREAD

**Issue by yrabun** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#236]
At this page of the site - https://www.fivefifthsvoter.com/#/votersupport

The following wording appears at the bottom: 

_Each voter’s journey is different. Five Fifths Voter can put you on the right path to reclaiming voter confidence. Please visit our support channels to help guide you._

I recommend we update it to read: 

Each voter’s journey is different. Five Fifths Voter **is designed to** put you on the right path to **help** reclaim voter confidence. 

For this sentence: 

Please visit our _**support channels**_ to help guide you.

What support channels are we referring to here? Should this be hyperlinked somewhere or do we need to delete this reference?

**Comment by Sabine-Justilien** [comment]
I agree with this language change. @upkarlidder can we replace the following

_Each voter’s journey is different. Five Fifths Voter can put you on the right path to reclaiming voter confidence. Please visit our support channels to help guide you._

with 

Each voter’s journey is different. Five Fifths Voter is designed to put you on the right path to help reclaim voter confidence. _Please visit the Five Fifths Voter [Github rep](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter) to explore the future of this opensource project and [Call for Code for Racial Justice](https://developer.ibm.com/callforcode/racial-justice/)._

cc: @yrabun

**Comment by GeraldMit** [comment]
Framing of this line is tricky in that it may differ for different implementations significantly.
Are this github repo and developer IBM needed for the statement as there are referenced by each other maybe we only need one?

ui/src/plugins/en.json
  "supportDesc": "Each voter’s journey is different. {0} can put you on the right path to reclaiming voter confidence. 
Please visit {1} for more information on {0}.",

**Comment by aleggett23** [comment]
@yrabun I agree that the wording may be a bit misleading where it is placed. When I initially wrote the script, I thought it would be placed above the links. The term "support channels" was in reference to the resource links shown on the page.

I do like @Sabine-Justilien suggestion; I think in the future, when we create a "get connected" tab, it may be better placed there. 

@GeraldMit thank you for highlighting that; i think the differentiation is that the cfcrj link takes users to information on the project and organization at large, while the Github repo shows the technical interface. I think we could play with the wording but I think both have value to include.

**Comment by Sabine-Justilien** [comment]
Current Language: 

_Each voter’s journey is different. Five Fifths Voter can put you on the right path to reclaiming voter confidence. Please visit our support channels to help guide you._

replace with

**Each voter’s journey is different. Five Fifths Voter is designed to put you on the right path to help reclaim voter confidence.**

This sentence should follow after "Resources are available to help you" and before the hotlinks

<img width="796" alt="Screen Shot 2021-09-27 at 5 49 54 PM" src="https://user-images.githubusercontent.com/83599562/134995707-5e656359-a591-41ae-9e61-2349a6438dab.png">
--

@GeraldMit @yrabun @aleggett23 Taking out the last sentence around support channels since this isn't a current capability and redirecting to the GH may further confuse someone. We do have [phone numbers](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/206) that people can call if they are experiencing voter issues which we can add to a 'Get Connected' section.

**Comment by upkarlidder** [comment]
The following was implemented:

Current Language:

Each voter’s journey is different. Five Fifths Voter can put you on the right path to reclaiming voter confidence. Please visit our support channels to help guide you.

replace with

Each voter’s journey is different. Five Fifths Voter is designed to put you on the right path to help reclaim voter confidence.

**Comment by davidnixon** [comment]
@Sabine-Justilien I think this can be closed. Upkar implemented this one.

**Comment by Sabine-Justilien** [comment]
LGTM - the language will be updated and issue #253 will continue the conversation on a new tab for getting connected.
