### ISSUE TITLE
After moving through the hamburger menu, it’s not obvious how to return to the main screen

### ISSUE THREAD

**Issue by cstefano1** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#292]
**Describe the bug**
The “hamburger” menu – when I’m on the home screen and select, say, Why Vote from the menu, it’s not obvious how to return to the main screen.  (I found that I can do that by clicking “Five Fifths Voter at the top”.)  

**To Reproduce**
1. Go to hamburger menu
2. Click on Voter Journey
3. How to return to the main screen....?

**Expected behavior**
Maybe have Five Fifths Voter on the hamburger menu?  Maybe a Home icon?

**Screenshots**
![image](https://user-images.githubusercontent.com/35705510/139347786-4d7566bd-d331-4205-9093-a67cb34f8b93.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android
 - Browser: N/A (in the 5/5ths app)
 - Version 11

**Additional context**

**Comment by upkarlidder** [comment]
Good observation @cstefano1. There are three ways to get out. And a fourth one that you discovered.

1. Click on the close button in the menu itself.
2. Click anywhere outside the menu. This is hard due to the small real estate.
3. Pick an option in the menu.
4. Click on `Five Fifths Voter` as you discovered.

We should look at design guidelines by [carbon](https://www.carbondesignsystem.com/) and others to see if there is a better usability design. Tagging @sebastianhuynh-nyc for input.
