### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by drealuc** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#78]
@eveandsn @mdboone06 Please provide a status on this issue

**Comment by davidnixon** [comment]
Can this be closed and tracked with #117 ?

**Comment by Sabine-Justilien** [comment]
The current version of 5/5 Voter does not collect any personal information (PI) wherein a privacy statement would be required. In the future, if the solution is developed to collect PI we will need to know what PI is being collected, how it is being handled, stored, and safeguarded. 

I am closing this issue because a new issue will be required with more detail around processing once additional capabilities are built within 5/5.
